# Generated by Django 4.1.4 on 2022-12-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
